# -*- coding: utf-8 -*-
"""
Created on Fri Jun 28 16:03:26 2019

@author: alauren
"""
import datetime

def para_ash():
        sites ={
        'ansa_cont':{'wfile': 'muhos_weather.csv','mottifile':'susi_ansa_cont.xlsx', 'ddepth': -0.45, 'Swidth': 40.,
                  'vonP':[6,6,5,4,6,6], 'ptype':['A','A','A','A','A','A'], 'start_date':datetime.datetime(2014,1,1), 
                  'end_date':datetime.datetime(2020,12,31), 'bulk dens':128.7, 'vol':[132.0, 155.0], 
                  'sfc':3, 'hdom': [13.8,14.4], 'mark':'bo', 'Aini':50, 'depoN': 4.0, 'depoP': 0.1,
                  'depoK': 0.65, 'LUE_multiplier': 1., 'fertilization': {
                  'application year': 2014,
                  'N':{'dose': 0.0, 'decay_k': 0.5, 'eff': 0.3},                              # fertilization dose in kg ha-1, decay_k in yr-1
                  'P':{'dose': 0.0, 'decay_k': 0.2, 'eff': 0.3},
                  'K':{'dose': 0.0, 'decay_k': 0.4, 'eff': 0.3}},  
                    },
                     
        'ansa_fert_0':{'wfile': 'muhos_weather.csv', 'mottifile':'susi_ansa_fert_0.xlsx','ddepth': -0.45, 'Swidth': 40.,
                  'vonP':[6,6,5,4,6,6], 'ptype':['A','A','A','A','A','A'], 'start_date':datetime.datetime(2014,1,1), 
                  'end_date':datetime.datetime(2020,12,31), 'bulk dens':128.7, 'vol':[129.5,158.3], 
                  'sfc':3, 'hdom': [14.1, 15.1], 'mark':'bo', 'Aini':48, 'depoN': 4.0, 'depoP': 0.1,
                  'depoK': 0.65, 'LUE_multiplier': 1., 'fertilization': {
                  'application year': 2014,
                  'N':{'dose': 0.0, 'decay_k': 0.5, 'eff': 0.3},                              # fertilization dose in kg ha-1, decay_k in yr-1
                  'P':{'dose': 0.0, 'decay_k': 0.2, 'eff': 0.3},
                  'K':{'dose': 0.0, 'decay_k': 0.4, 'eff': 0.3}},
                    },
                          
        'ansa_fert_1':{'wfile': 'muhos_weather.csv', 'mottifile':'susi_ansa_fert_1.xlsx','ddepth': -0.45, 'Swidth': 40.,
                  'vonP':[6,6,5,4,6,6], 'ptype':['A','A','A','A','A','A'], 'start_date':datetime.datetime(2014,1,1), 
                  'end_date':datetime.datetime(2020,12,31), 'bulk dens':128.7, 'vol':[129.5,158.3], 
                  'sfc':3, 'hdom': [14.1, 15.1], 'mark':'bo', 'Aini':48, 'depoN': 4.0, 'depoP': 0.1,
                  'depoK': 0.65, 'LUE_multiplier': 1.0, 'fertilization': {
                  'application year': 2014,
                  'N':{'dose': 0.0, 'decay_k': 0.5, 'eff': 0.3},                              # fertilization dose in kg ha-1, decay_k in yr-1
                  'P':{'dose': 0.0, 'decay_k': 0.2, 'eff': 0.3},
                  'K':{'dose': 0.0, 'decay_k': 0.4, 'eff': 0.3}},
                    },

        'ansa_fert_2':{'wfile': 'muhos_weather.csv', 'mottifile':'susi_ansa_fert_1.xlsx','ddepth': -0.45, 'Swidth': 40.,
                  'vonP':[6,6,5,4,6,6], 'ptype':['A','A','A','A','A','A'], 'start_date':datetime.datetime(2014,1,1), 
                  'end_date':datetime.datetime(2020,12,31), 'bulk dens':128.7, 'vol':[129.5,158.3], 
                  'sfc':3, 'hdom': [14.1, 15.1], 'mark':'bo', 'Aini':48, 'depoN': 4.0, 'depoP': 0.1,
                  'depoK': 0.65, 'LUE_multiplier': 1.2, 'fertilization': {
                  'application year': 2014,
                  'N':{'dose': 0.0, 'decay_k': 0.5, 'eff': 0.3},                              # fertilization dose in kg ha-1, decay_k in yr-1
                  'P':{'dose': 0.0, 'decay_k': 0.2, 'eff': 0.3},
                  'K':{'dose': 0.0, 'decay_k': 0.4, 'eff': 0.3}},
                    },

        'ansa_fert_3':{'wfile': 'muhos_weather.csv', 'mottifile':'susi_ansa_fert_1.xlsx','ddepth': -0.45, 'Swidth': 40.,
                  'vonP':[6,6,5,4,6,6], 'ptype':['A','A','A','A','A','A'], 'start_date':datetime.datetime(2014,1,1), 
                  'end_date':datetime.datetime(2020,12,31), 'bulk dens':128.7, 'vol':[129.5,158.3], 
                  'sfc':3, 'hdom': [14.1, 15.1], 'mark':'bo', 'Aini':48, 'depoN': 4.0, 'depoP': 0.1,
                  'depoK': 0.65, 'LUE_multiplier': 1.2, 'fertilization': {
                  'application year': 2014,
                  'N':{'dose': 0.0, 'decay_k': 0.5, 'eff': 0.3},                              # fertilization dose in kg ha-1, decay_k in yr-1
                  'P':{'dose': 45.0, 'decay_k': 0.2, 'eff': 0.3},
                  'K':{'dose': 117.0, 'decay_k': 0.4, 'eff': 0.3}},
                    },
        
        
        'koira_cont':{'wfile': 'koirasuo_weather.csv', 'mottifile':'susi_koira_cont.xlsx','ddepth': -0.85, 'Swidth': 37.,
                   'vonP':[4,4,5,6,7,7], 'ptype':['A','A','A','A','A','A'], 'start_date':datetime.datetime(2014,1,1), 
                  'end_date':datetime.datetime(2020,12,31),'bulk dens':108.6, 'vol':[149.0,163.0,], 
                  'sfc':2, 'hdom': [13.9, 14.4], 'mark':'bs', 'Aini':92, 'depoN': 4.0, 'depoP': 0.1,
                  'depoK': 0.65, 'LUE_multiplier': 1.,'fertilization': {
                  'application year': 2014,
                  'N':{'dose': 0.0, 'decay_k': 0.5, 'eff': 0.3},                              # fertilization dose in kg ha-1, decay_k in yr-1
                  'P':{'dose': 0.0, 'decay_k': 0.2, 'eff': 0.3},
                  'K':{'dose': 0.0, 'decay_k': 0.4, 'eff': 0.3}},
                    },
                      
        'koira_fert_0':{'wfile': 'koirasuo_weather.csv', 'mottifile':'susi_koira_fert_0.xlsx','ddepth': -0.85, 'Swidth': 37.,
                   'vonP':[4,4,5,6,6,6], 'ptype':['A','A','A','A','A','A'], 'start_date':datetime.datetime(2014,1,1), 
                  'end_date':datetime.datetime(2020,12,31), 'bulk dens':108.6, 'vol':[92.0,113.0], 
                  'sfc':2, 'hdom': [14.7, 15.8], 'mark':'rs', 'Aini':80, 'depoN': 4.0, 'depoP': 0.1,
                  'depoK': 0.65,'LUE_multiplier': 1., 'fertilization': {
                  'application year': 2014,
                  'N':{'dose': 0.0, 'decay_k': 0.5, 'eff': 0.3},                              # fertilization dose in kg ha-1, decay_k in yr-1
                  'P':{'dose': 0.0, 'decay_k': 0.2, 'eff': 0.3},
                  'K':{'dose': 0.0, 'decay_k': 0.4, 'eff': 0.3},},
                    },
 
        'koira_fert_1':{'wfile': 'koirasuo_weather.csv', 'mottifile':'susi_koira_fert_1.xlsx','ddepth': -0.85, 'Swidth': 37.,
                   'vonP':[4,4,5,6,6,6], 'ptype':['A','A','A','A','A','A'], 'start_date':datetime.datetime(2014,1,1), 
                  'end_date':datetime.datetime(2020,12,31), 'bulk dens':108.6, 'vol':[92.0,113.0], 
                  'sfc':2, 'hdom': [14.7, 15.8], 'mark':'rs', 'Aini':80, 'depoN': 4.0, 'depoP': 0.1,
                  'depoK': 0.65,'LUE_multiplier': 1.0,'fertilization': {
                  'application year': 2014,
                  'N':{'dose': 0.0, 'decay_k': 0.5, 'eff': 0.3},                              # fertilization dose in kg ha-1, decay_k in yr-1
                  'P':{'dose': 0.0, 'decay_k': 0.2, 'eff': 0.3},
                  'K':{'dose': 0.0, 'decay_k': 0.4, 'eff': 0.3}},
                      },

        'koira_fert_2':{'wfile': 'koirasuo_weather.csv', 'mottifile':'susi_koira_fert_1.xlsx','ddepth': -0.85, 'Swidth': 37.,
                   'vonP':[4,4,5,6,6,6], 'ptype':['A','A','A','A','A','A'], 'start_date':datetime.datetime(2014,1,1), 
                  'end_date':datetime.datetime(2020,12,31), 'bulk dens':108.6, 'vol':[92.0,113.0], 
                  'sfc':2, 'hdom': [14.7, 15.8], 'mark':'rs', 'Aini':80, 'depoN': 4.0, 'depoP': 0.1,
                  'depoK': 0.65,'LUE_multiplier': 1.2,'fertilization': {
                  'application year': 2014,
                  'N':{'dose': 0.0, 'decay_k': 0.5, 'eff': 0.3},                              # fertilization dose in kg ha-1, decay_k in yr-1
                  'P':{'dose': 0.0, 'decay_k': 0.2, 'eff': 0.3},
                  'K':{'dose': 0.0, 'decay_k': 0.4, 'eff': 0.3}},
                      },

        'koira_fert_3':{'wfile': 'koirasuo_weather.csv', 'mottifile':'susi_koira_fert_1.xlsx','ddepth': -0.85, 'Swidth': 37.,
                   'vonP':[4,4,5,6,6,6], 'ptype':['A','A','A','A','A','A'], 'start_date':datetime.datetime(2014,1,1), 
                  'end_date':datetime.datetime(2020,12,31), 'bulk dens':108.6, 'vol':[92.0,113.0], 
                  'sfc':2, 'hdom': [14.7, 15.8], 'mark':'rs', 'Aini':80, 'depoN': 4.0, 'depoP': 0.1,
                  'depoK': 0.65,'LUE_multiplier': 1.2,'fertilization': {
                  'application year': 2014,
                  'N':{'dose': 0.0, 'decay_k': 0.5, 'eff': 0.3},                              # fertilization dose in kg ha-1, decay_k in yr-1
                  'P':{'dose': 43.0, 'decay_k': 0.2, 'eff': 0.3},
                  'K':{'dose': 45.0, 'decay_k': 0.4, 'eff': 0.3}},
                      },
    
        'neva_cont':{'wfile': 'nevajarvi_weather.csv', 'mottifile':'susi_neva_cont.xlsx','ddepth': -1.03, 'Swidth': 25.,
                  'vonP':[5,5,5,4,4,4], 'ptype':['A','A','A','A','A','A'], 'start_date':datetime.datetime(2014,1,1), 
                  'end_date':datetime.datetime(2020,12,31), 'bulk dens':113.25, 'vol':[203.0,225.0], 
                  'sfc':3, 'hdom': [16.1, 17.8], 'mark':'b+', 'Aini':105, 'depoN': 4.0, 'depoP': 0.1,
                  'depoK': 0.65, 'LUE_multiplier': 1.,'fertilization': {
                  'application year': 2014,
                  'N':{'dose': 0.0, 'decay_k': 0.5, 'eff': 0.3},                              # fertilization dose in kg ha-1, decay_k in yr-1
                  'P':{'dose': 0.0, 'decay_k': 0.2, 'eff': 0.3},
                  'K':{'dose': 0.0, 'decay_k': 0.4, 'eff': 0.3}},
                    },

        'neva_fert_0':{'wfile': 'nevajarvi_weather.csv','mottifile':'susi_neva_fert_0.xlsx','ddepth': -1.07, 'Swidth': 30.,
                  'vonP':[4,4,4,4,4,4], 'ptype':['A','A','A','A','A','A'], 'start_date':datetime.datetime(2014,1,1), 
                  'end_date':datetime.datetime(2020,12,31), 'bulk dens':97.8, 'vol':[118.0, 146.0], 
                  'sfc':3, 'hdom': [17.3, 18.2], 'mark':'r+', 'Aini':80, 'depoN': 4.0, 'depoP': 0.1,
                  'depoK': 0.65, 'LUE_multiplier': 1.,'fertilization': {
                  'application year': 2014,
                  'N':{'dose': 0.0, 'decay_k': 0.5, 'eff': 0.3},                              # fertilization dose in kg ha-1, decay_k in yr-1
                  'P':{'dose': 0.0, 'decay_k': 0.2, 'eff': 0.3},
                  'K':{'dose': 0.0, 'decay_k': 0.4, 'eff': 0.3}},
                    },
                      
        'neva_fert_1':{'wfile': 'nevajarvi_weather.csv','mottifile':'susi_neva_fert_1.xlsx','ddepth': -1.07, 'Swidth': 30.,
                  'vonP':[4,4,4,4,4,4], 'ptype':['A','A','A','A','A','A'], 'start_date':datetime.datetime(2014,1,1), 
                  'end_date':datetime.datetime(2020,12,31), 'bulk dens':97.8, 'vol':[118.0, 146.0], 
                  'sfc':3, 'hdom': [17.3, 18.2], 'mark':'r+', 'Aini':80, 'depoN': 4.0, 'depoP': 0.1,
                  'depoK': 0.65, 'LUE_multiplier': 1.0,'fertilization': {
                  'application year': 2014,
                  'N':{'dose': 0.0, 'decay_k': 0.5, 'eff': 0.3},                              # fertilization dose in kg ha-1, decay_k in yr-1
                  'P':{'dose': 0.0, 'decay_k': 0.2, 'eff': 0.3},
                  'K':{'dose': 0.0, 'decay_k': 0.4, 'eff': 0.3}},
                    },

        'neva_fert_2':{'wfile': 'nevajarvi_weather.csv','mottifile':'susi_neva_fert_1.xlsx','ddepth': -1.07, 'Swidth': 30.,
                  'vonP':[4,4,4,4,4,4], 'ptype':['A','A','A','A','A','A'], 'start_date':datetime.datetime(2014,1,1), 
                  'end_date':datetime.datetime(2020,12,31), 'bulk dens':97.8, 'vol':[118.0, 146.0], 
                  'sfc':3, 'hdom': [17.3, 18.2], 'mark':'r+', 'Aini':80, 'depoN': 4.0, 'depoP': 0.1,
                  'depoK': 0.65, 'LUE_multiplier': 1.2,'fertilization': {
                  'application year': 2014,
                  'N':{'dose': 0.0, 'decay_k': 0.5, 'eff': 0.3},                              # fertilization dose in kg ha-1, decay_k in yr-1
                  'P':{'dose': 0.0, 'decay_k': 0.2, 'eff': 0.3},
                  'K':{'dose': 0.0, 'decay_k': 0.4, 'eff': 0.3}},
                    },

        'neva_fert_3':{'wfile': 'nevajarvi_weather.csv','mottifile':'susi_neva_fert_1.xlsx','ddepth': -1.07, 'Swidth': 30.,
                  'vonP':[4,4,4,4,4,4], 'ptype':['A','A','A','A','A','A'], 'start_date':datetime.datetime(2014,1,1), 
                  'end_date':datetime.datetime(2020,12,31), 'bulk dens':97.8, 'vol':[118.0, 146.0], 
                  'sfc':3, 'hdom': [17.3, 18.2], 'mark':'r+', 'Aini':80, 'depoN': 4.0, 'depoP': 0.1,
                  'depoK': 0.65, 'LUE_multiplier': 1.2,'fertilization': {
                  'application year': 2014,
                  'N':{'dose': 0.0, 'decay_k': 0.5, 'eff': 0.3},                              # fertilization dose in kg ha-1, decay_k in yr-1
                  'P':{'dose': 45.0, 'decay_k': 0.2, 'eff': 0.3},
                  'K':{'dose': 117.0, 'decay_k': 0.4, 'eff': 0.3}},
                    },
                       
        }

        return sites

#ansa21, 26 'vonP':[6,6,5,4,6,6]
def para(period='start-end'):
    sites ={
        'start-end':{
        'ansa21':{'ntubes':6, 'file': 'DWTansa21Interp.csv', 'wfile': 'muhos_weather.csv',
                  'mottifile':'ansa21_A.xls', 'ddepth': -0.45, 'Swidth': 40.,
                  'vonP':[2,3,4,4,6,6], 'ptype':['A','A','A','A','A','A'], 'start_date':datetime.datetime(2008,1,1), 
                  'end_date':datetime.datetime(2014,12,31), 'status': 'wet', 'bulk dens':128.7, 'thinning': False,
                  'vol':[140.0, 187.07], 'sfc':3, 'hdom': [12.8,14.6], 'mark':'bo', 'Aini':39, 'depoN': 4.0, 'depoP': 0.1,
                  'depoK': 0.65},
        'ansa26':{'ntubes':3, 'file': 'DWTansa26Interp.csv', 'wfile': 'muhos_weather.csv',
                  'mottifile':'ansa26_A.xls','ddepth': -0.45, 'Swidth': 40.,
                  'vonP':[2,3,4,4,6,6], 'ptype':['A','A','A','A','A','A'], 'start_date':datetime.datetime(2008,1,1), 
                  'end_date':datetime.datetime(2014,12,31), 'status': 'dry','bulk dens':128.7, 'thinning': False,
                  'vol':[109.9,140.86], 'sfc':3, 'hdom': [12.6, 15.4], 'mark':'bo', 'Aini':39, 'depoN': 4.0, 'depoP': 0.1,
                  'depoK': 0.55},
        'jaakkoin61':{'ntubes':6, 'file': 'DWTjaakkoin61Interp.csv', 'wfile': 'jaakkoinsuo_weather.csv',
                  'mottifile':'jaakkoin61_A.xls','ddepth': -0.85, 'Swidth': 40.,
                  'vonP':[4,8,7,7,7,7], 'ptype':['A','A','A','A','A','A'], 'start_date':datetime.datetime(2007,1,1), 
                  'end_date':datetime.datetime(2013,12,31), 'status': 'wet','bulk dens':134., 'thinning': False,
                  'vol':[144.3,172.6], 'sfc':5, 'hdom': [17.6, 18.5], 'mark':'b*', 'Aini':86,'depoN': 4.0, 'depoP': 0.1,
                  'depoK': 0.95},
        'jaakkoin62':{'ntubes':8, 'file': 'DWTjaakkoin62Interp.csv', 'wfile': 'jaakkoinsuo_weather.csv',
                  'mottifile':'jaakkoin62_A.xls','ddepth': -0.85, 'Swidth': 40.,
                  'vonP':[4,8,7,7,7,7], 'ptype':['A','A','A','A','A','A'], 'start_date':datetime.datetime(2007,1,1), 
                  'end_date':datetime.datetime(2013,12,31), 'status': 'dry','bulk dens':134., 'thinning': False,
                  'vol':[149.3,186.6], 'sfc':5, 'hdom': [18.1, 19.5], 'mark':'b*', 'Aini':86, 'depoN': 4.0, 'depoP': 0.1,
                  'depoK': 0.95},
        'koira11':{'ntubes':3, 'file': 'DWTkoira11Interp.csv', 'wfile': 'koirasuo_weather.csv',
                  'mottifile':'koira11_A.xls','ddepth': -0.85, 'Swidth': 37.,
                   'vonP':[4,4,5,6,7,7], 'ptype':['A','A','A','A','A','A'], 'start_date':datetime.datetime(2008,1,1), 
                  'end_date':datetime.datetime(2014,12,31), 'status': 'wet','bulk dens':108.6, 'thinning': False,
                  'vol':[90.9,122.], 'sfc':2, 'hdom': [12.9, 13.9], 'mark':'bs', 'Aini':76, 'depoN': 4.0, 'depoP': 0.1,
                  'depoK': 0.65},
        'koira12':{'ntubes':3, 'file': 'DWTkoira12Interp.csv', 'wfile': 'koirasuo_weather.csv',
                  'mottifile':'koira12_A.xls','ddepth': -0.85, 'Swidth': 37.,
                   'vonP':[4,4,5,6,6,6], 'ptype':['A','A','A','A','A','A'], 'start_date':datetime.datetime(2008,1,1), 
                  'end_date':datetime.datetime(2014,12,31), 'status': 'dry','bulk dens':108.6, 'thinning': False,
                  'vol':[122.9,164.], 'sfc':2, 'hdom': [13.2,16.4], 'mark':'bs', 'Aini':76, 'depoN': 4.0, 'depoP': 0.1,
                  'depoK': 0.65},       
        'koira21':{'ntubes':3, 'file': 'DWTkoira21Interp.csv', 'wfile': 'koirasuo_weather.csv',
                  'mottifile':'koira21_harvennus_A.xls','ddepth': -0.85, 'Swidth': 37.,
                   'vonP':[4,4,5,6,6,6], 'ptype':['A','A','A','A','A','A'], 'start_date':datetime.datetime(2008,1,1), 
                  'end_date':datetime.datetime(2009,12,31), 'status': 'wet','bulk dens':108.6, 'thinning': True,
                  'vol':[97.4,91.9+30.6], 'sfc':2, 'hdom': [12.7, 14.5], 'mark':'rs', 'Aini':76, 'depoN': 4.0, 'depoP': 0.1,
                  'depoK': 0.65},        
        'koira22':{'ntubes':3, 'file': 'DWTkoira22Interp.csv', 'wfile': 'koirasuo_weather.csv',
                  'mottifile':'koira22_harvennus_A.xls','ddepth': -0.85, 'Swidth': 37.,
                   'vonP':[4,4,5,6,6,6], 'ptype':['A','A','A','A','A','A'], 'start_date':datetime.datetime(2008,1,1), 
                  'end_date':datetime.datetime(2009,12,31), 'status': 'dry','bulk dens':108.6, 'thinning': True,
                  'vol':[92.2,87.13+33.92], 'sfc':2, 'hdom': [11.1,14.3], 'mark':'rs', 'Aini':76, 'depoN': 4.0, 'depoP': 0.1,
                  'depoK': 0.95},
        'neva11':{'ntubes':6, 'file': 'DWTneva11Interp.csv', 'wfile': 'nevajarvi_weather.csv',
                  'mottifile':'neva11_A.xls','ddepth': -1.03, 'Swidth': 30.,
                  'vonP':[5,5,5,4,4,4], 'ptype':['A','A','A','A','A','A'], 'start_date':datetime.datetime(2007,1,1), 
                  'end_date':datetime.datetime(2014,12,31), 'status': 'dry','bulk dens':113.25, 'thinning': False,
                  'vol':[163.4,227.5], 'sfc':3, 'hdom': [16.1, 17.8], 'mark':'b+', 'Aini':80, 'depoN': 4.0, 'depoP': 0.1,
                  'depoK': 0.65},
        'neva14':{'ntubes':6, 'file': 'DWTneva14Interp.csv', 'wfile': 'nevajarvi_weather.csv',
                  'mottifile':'neva14_A.xls', 'ddepth': -1.03, 'Swidth': 30.,
                  'vonP':[5,5,5,4,4,4], 'ptype':['A','A','A','A','A','A'], 'start_date':datetime.datetime(2007,1,1), 
                  'end_date':datetime.datetime(2014,12,31), 'status': 'wet','bulk dens':113.25, 'thinning': False,
                  'vol': [142.9, 191.4], 'sfc':3, 'hdom': [16.5, 18.4], 'mark':'b+', 'Aini':80, 'depoN': 4.0, 'depoP': 0.1,
                  'depoK': 0.65},
        'neva21':{'ntubes':7, 'file': 'DWTneva21Interp.csv', 'wfile': 'nevajarvi_weather.csv',
                  'mottifile':'neva21_harvennus_A.xls','ddepth': -1.07, 'Swidth': 30.,
                  'vonP':[4,4,4,4,4,4], 'ptype':['A','A','A','A','A','A'], 'start_date':datetime.datetime(2007,1,1), 
                  'end_date':datetime.datetime(2008,12,31), 'status': 'dry','bulk dens':97.8, 'thinning': True,
                  'vol':[100.32, 109.89+32.5], 'sfc':3, 'hdom': [15.7, 16.7], 'mark':'r+', 'Aini':80, 'depoN': 4.0, 'depoP': 0.1,
                  'depoK': 0.65},   
        'neva24':{'ntubes':6, 'file': 'DWTneva24Interp.csv', 'wfile': 'nevajarvi_weather.csv',
                  'mottifile':'neva24_harvennus_A.xls','ddepth': -1.07, 'Swidth': 30.,
                  'vonP':[4,4,4,4,4,4], 'ptype':['A','A','A','A','A','A'], 'start_date':datetime.datetime(2007,1,1), 
                  'end_date':datetime.datetime(2008,12,31), 'status': 'wet','bulk dens':97.8, 'thinning': True,
                  'vol':[143.6, 124.7+53.66], 'sfc':3, 'hdom': [14.6, 17.1], 'mark':'r+', 'Aini':80, 'depoN': 4.0, 'depoP': 0.1,
                  'depoK': 0.65},
        'neva31':{'ntubes':10, 'file': 'DWTneva31Interp.csv', 'wfile': 'nevajarvi_weather.csv',
                  'mottifile':'neva31_A.xls', 'ddepth': -1.08, 'Swidth': 30.,
                  'vonP':[5,5,4,5,5,5], 'ptype':['A','A','A','A','A','A'], 'start_date':datetime.datetime(2007,1,1), 
                  'end_date':datetime.datetime(2014,12,31), 'status': 'dry','bulk dens':122.5, 'thinning': False,
                  'vol':[127.2, 161.5], 'sfc':3, 'hdom': [16.5, 17.0], 'mark':'b+', 'Aini':80, 'depoN': 4.0, 'depoP': 0.1,
                  'depoK': 0.65},
        'neva34':{'ntubes':10, 'file': 'DWTneva34Interp.csv', 'wfile': 'nevajarvi_weather.csv',
                  'mottifile':'neva34_A.xls','ddepth': -1.08, 'Swidth': 30.,
                  'vonP':[5,5,4,5,5,5], 'ptype':['A','A','A','A','A','A'], 'start_date':datetime.datetime(2007,1,1), 
                  'end_date':datetime.datetime(2014,12,31), 'status': 'wet','bulk dens':122.5, 'thinning': False,
                  'vol':[100.4, 147.3], 'sfc':3, 'hdom': [15.3,17.1], 'mark':'b+', 'Aini':80, 'depoN': 4.0, 'depoP': 0.1,
                  'depoK': 0.65},
        'parkano11':{'ntubes':12, 'file': 'DWTparkano11Interp.csv', 'wfile': 'parkano_weather.csv',
                  'mottifile':'parkano11_A.xls','ddepth': -0.86, 'Swidth': 65.,
                  'vonP':[3,3,6,6,6,6], 'ptype':['S','S','S','S','S','S'], 'start_date':datetime.datetime(2007,1,1), 
                  'end_date':datetime.datetime(2011,12,31), 'status': 'dry','bulk dens':99.35, 'thinning': False,
                  'vol':[167.7, 192.4], 'sfc':3, 'hdom': [17.3, 18.7], 'mark':'bD', 'Aini':130, 'depoN': 4.0, 'depoP': 0.1,
                  'depoK': 0.95},
        'parkano12':{'ntubes':14, 'file': 'DWTparkano12Interp.csv', 'wfile': 'parkano_weather.csv',
                  'mottifile':'parkano12_harvennus_A.xls','ddepth': -0.89, 'Swidth': 65.,
                  'vonP':[3,5,6,6,6,6], 'ptype':['A','A','A','A','A','A'], 'start_date':datetime.datetime(2007,1,1), 
                  'end_date':datetime.datetime(2009,12,31), 'status': 'wet','bulk dens':99.35, 'thinning': True,
                  'vol':[263., 173.+112.9], 'sfc':5, 'hdom': [20.0, 20.7], 'mark':'rD', 'Aini':130, 'depoN': 4.0, 'depoP': 0.1,
                  'depoK': 0.95},

        #'ansa11':{'ntubes':6, 'file': 'DWTansa11Interp.csv', 'wfile': 'muhos_weather.csv',
        #          'mottifile':'ansa11_harvennus_A.xls', 'ddepth': -0.25, 'Swidth': 40.,
        #          'vonP':[4,6,6,6,6,6], 'ptype':['A','A','A','A','A','A'], 'start_date':datetime.datetime(2008,1,1), 
        #          'end_date':datetime.datetime(2009,12,31), 'status': 'wet', 'bulk dens':122.6, 'thinning': True,
        #          'vol':[94.5,121.31+7.19], 'sfc':3, 'hdom': [11.9, 13.3], 'mark':'ro', 'Aini':39},
        #'ansa16':{'ntubes':3, 'file': 'DWTansa16Interp.csv', 'wfile': 'muhos_weather.csv',
        #          'mottifile':'ansa16_harvennus_A.xls', 'ddepth': -0.25, 'Swidth': 40.,
        #          'vonP':[4,6,6,6,6,6], 'ptype':['A','A','A','A','A','A'], 'start_date':datetime.datetime(2008,1,1), 
        #          'end_date':datetime.datetime(2009,12,31), 'status': 'dry', 'bulk dens':122.6, 'thinning': True,
        #          'vol':[143.2, 135.3+42.15], 'sfc':3, 'hdom': [13.1, 15.3], 'mark':'ro', 'Aini':39},
      
        },
        'start-thin':{
            'ansa11':{'ntubes':6, 'file': 'DWTansa11Interp.csv', 'wfile': 'muhos_weather.csv',
                      'mottifile':'ansa11_harvennus_A.xls', 'ddepth': -0.25, 'Swidth': 40.,
                      'vonP':[4,6,6,6,6,6], 'ptype':['A','A','A','A','A','A'], 'start_date':datetime.datetime(2008,1,1), 
                      'end_date':datetime.datetime(2009,12,31), 'status': 'wet', 'bulk dens':122.6, 'thinning': True,
                      'vol':[94.5,105.33], 'sfc':3, 'hdom': [11.9, 13.3], 'mark':'ro', 'Aini':35, 'depoN': 4.0, 'depoP': 0.1,
                      'depoK': 0.65},
            'ansa16':{'ntubes':3, 'file': 'DWTansa16Interp.csv', 'wfile': 'muhos_weather.csv',
                      'mottifile':'ansa16_harvennus_A.xls', 'ddepth': -0.25, 'Swidth': 40.,
                      'vonP':[4,6,6,6,6,6], 'ptype':['A','A','A','A','A','A'], 'start_date':datetime.datetime(2008,1,1), 
                      'end_date':datetime.datetime(2009,12,31), 'status': 'dry', 'bulk dens':122.6, 'thinning': True,
                      'vol':[143.2,149.7], 'sfc':3, 'hdom': [13.1, 15.3], 'mark':'ro', 'Aini':35, 'depoN': 4.0, 'depoP': 0.1,
                      'depoK': 0.65},
           'ansa21':{'ntubes':6, 'file': 'DWTansa21Interp.csv', 'wfile': 'muhos_weather.csv',
                      'mottifile':'ansa21_A.xls', 'ddepth': -0.45, 'Swidth': 40.,
                      'vonP':[2,3,4,4,6,6], 'ptype':['A','A','A','A','A','A'], 'start_date':datetime.datetime(2008,1,1), 
                      'end_date':datetime.datetime(2014,12,31), 'status': 'wet', 'bulk dens':128.7, 'thinning': False,
                      'vol':[140.0, 187.07], 'sfc':3, 'hdom': [12.8,14.6], 'mark':'bo', 'Aini':39, 'depoN': 4.0, 'depoP': 0.1,
                      'depoK': 0.65},
            'ansa26':{'ntubes':3, 'file': 'DWTansa26Interp.csv', 'wfile': 'muhos_weather.csv',
                      'mottifile':'ansa26_A.xls','ddepth': -0.45, 'Swidth': 40.,
                      'vonP':[2,3,4,4,6,6], 'ptype':['A','A','A','A','A','A'], 'start_date':datetime.datetime(2008,1,1), 
                      'end_date':datetime.datetime(2014,12,31), 'status': 'dry','bulk dens':128.7, 'thinning': False,
                      'vol':[109.9,140.86], 'sfc':3, 'hdom': [12.6, 15.4], 'mark':'bo', 'Aini':39, 'depoN': 4.0, 'depoP': 0.1,
                      'depoK': 0.55},
            'jaakkoin61':{'ntubes':6, 'file': 'DWTjaakkoin61Interp.csv', 'wfile': 'jaakkoinsuo_weather.csv',
                      'mottifile':'jaakkoin61_A.xls','ddepth': -0.85, 'Swidth': 40.,
                      'vonP':[4,8,7,7,7,7], 'ptype':['A','A','A','A','A','A'], 'start_date':datetime.datetime(2007,1,1), 
                      'end_date':datetime.datetime(2013,12,31), 'status': 'wet','bulk dens':134., 'thinning': False,
                      'vol':[144.3,172.6], 'sfc':5, 'hdom': [17.6, 18.5], 'mark':'b*', 'Aini':86,'depoN': 4.0, 'depoP': 0.1,
                      'depoK': 0.95},
            'jaakkoin62':{'ntubes':8, 'file': 'DWTjaakkoin62Interp.csv', 'wfile': 'jaakkoinsuo_weather.csv',
                      'mottifile':'jaakkoin62_A.xls','ddepth': -0.85, 'Swidth': 40.,
                      'vonP':[4,8,7,7,7,7], 'ptype':['A','A','A','A','A','A'], 'start_date':datetime.datetime(2007,1,1), 
                      'end_date':datetime.datetime(2013,12,31), 'status': 'dry','bulk dens':134., 'thinning': False,
                      'vol':[149.3,186.6], 'sfc':5, 'hdom': [18.1, 19.5], 'mark':'b*', 'Aini':86, 'depoN': 4.0, 'depoP': 0.1,
                      'depoK': 0.95},
            'koira11':{'ntubes':3, 'file': 'DWTkoira11Interp.csv', 'wfile': 'koirasuo_weather.csv',
                      'mottifile':'koira11_A.xls','ddepth': -0.85, 'Swidth': 37.,
                       'vonP':[4,4,5,6,7,7], 'ptype':['A','A','A','A','A','A'], 'start_date':datetime.datetime(2008,1,1), 
                      'end_date':datetime.datetime(2014,12,31), 'status': 'wet','bulk dens':108.6, 'thinning': False,
                      'vol':[90.9,122.], 'sfc':2, 'hdom': [12.9, 13.9], 'mark':'bs', 'Aini':76, 'depoN': 4.0, 'depoP': 0.1,
                      'depoK': 0.65},
            'koira12':{'ntubes':3, 'file': 'DWTkoira12Interp.csv', 'wfile': 'koirasuo_weather.csv',
                      'mottifile':'koira12_A.xls','ddepth': -0.85, 'Swidth': 37.,
                       'vonP':[4,4,5,6,6,6], 'ptype':['A','A','A','A','A','A'], 'start_date':datetime.datetime(2008,1,1), 
                      'end_date':datetime.datetime(2014,12,31), 'status': 'dry','bulk dens':108.6, 'thinning': False,
                      'vol':[122.9,164.], 'sfc':2, 'hdom': [13.2,16.4], 'mark':'bs', 'Aini':76, 'depoN': 4.0, 'depoP': 0.1,
                      'depoK': 0.65},       
            'koira21':{'ntubes':3, 'file': 'DWTkoira21Interp.csv', 'wfile': 'koirasuo_weather.csv',
                      'mottifile':'koira21_harvennus_A.xls','ddepth': -0.85, 'Swidth': 37.,
                       'vonP':[4,4,5,6,6,6], 'ptype':['A','A','A','A','A','A'], 'start_date':datetime.datetime(2008,1,1), 
                      'end_date':datetime.datetime(2009,12,31), 'status': 'wet','bulk dens':108.6, 'thinning': True,
                      'vol':[97.4, 105.92], 'sfc':2, 'hdom': [12.7, 14.5], 'mark':'rs', 'Aini':74, 'depoN': 4.0, 'depoP': 0.1,
                      'depoK': 0.65},        
            'koira22':{'ntubes':3, 'file': 'DWTkoira22Interp.csv', 'wfile': 'koirasuo_weather.csv',
                      'mottifile':'koira22_harvennus_A.xls','ddepth': -0.85, 'Swidth': 37.,
                       'vonP':[4,4,5,6,6,6], 'ptype':['A','A','A','A','A','A'], 'start_date':datetime.datetime(2008,1,1), 
                      'end_date':datetime.datetime(2009,12,31), 'status': 'dry','bulk dens':108.6, 'thinning': True,
                      'vol':[92.2, 106.24], 'sfc':2, 'hdom': [11.1,14.3], 'mark':'rs', 'Aini':70, 'depoN': 4.0, 'depoP': 0.1,
                      'depoK': 0.95},
            'neva11':{'ntubes':6, 'file': 'DWTneva11Interp.csv', 'wfile': 'nevajarvi_weather.csv',
                      'mottifile':'neva11_A.xls','ddepth': -1.03, 'Swidth': 30.,
                      'vonP':[5,5,5,4,4,4], 'ptype':['A','A','A','A','A','A'], 'start_date':datetime.datetime(2007,1,1), 
                      'end_date':datetime.datetime(2014,12,31), 'status': 'dry','bulk dens':113.25, 'thinning': False,
                      'vol':[163.4,227.5], 'sfc':3, 'hdom': [16.1, 17.8], 'mark':'b+', 'Aini':80, 'depoN': 4.0, 'depoP': 0.1,
                      'depoK': 0.65},
            'neva14':{'ntubes':6, 'file': 'DWTneva14Interp.csv', 'wfile': 'nevajarvi_weather.csv',
                      'mottifile':'neva14_A.xls', 'ddepth': -1.03, 'Swidth': 30.,
                      'vonP':[5,5,5,4,4,4], 'ptype':['A','A','A','A','A','A'], 'start_date':datetime.datetime(2007,1,1), 
                      'end_date':datetime.datetime(2014,12,31), 'status': 'wet','bulk dens':113.25, 'thinning': False,
                      'vol': [142.9, 191.4], 'sfc':3, 'hdom': [16.5, 18.4], 'mark':'b+', 'Aini':80, 'depoN': 4.0, 'depoP': 0.1,
                      'depoK': 0.65},
            'neva21':{'ntubes':7, 'file': 'DWTneva21Interp.csv', 'wfile': 'nevajarvi_weather.csv',
                      'mottifile':'neva21_harvennus_A.xls','ddepth': -1.07, 'Swidth': 30.,
                      'vonP':[4,4,4,4,4,4], 'ptype':['A','A','A','A','A','A'], 'start_date':datetime.datetime(2007,1,1), 
                      'end_date':datetime.datetime(2008,12,31), 'status': 'dry','bulk dens':97.8, 'thinning': True,
                      'vol':[100.32, 104.5], 'sfc':3, 'hdom': [15.7, 16.7], 'mark':'r+', 'Aini':72, 'depoN': 4.0, 'depoP': 0.1,
                      'depoK': 0.65},   
            'neva24':{'ntubes':6, 'file': 'DWTneva24Interp.csv', 'wfile': 'nevajarvi_weather.csv',
                      'mottifile':'neva24_harvennus_A.xls','ddepth': -1.07, 'Swidth': 30.,
                      'vonP':[4,4,4,4,4,4], 'ptype':['A','A','A','A','A','A'], 'start_date':datetime.datetime(2007,1,1), 
                      'end_date':datetime.datetime(2008,12,31), 'status': 'wet','bulk dens':97.8, 'thinning': True,
                      'vol':[143.6, 147.3], 'sfc':3, 'hdom': [14.6, 17.1], 'mark':'r+', 'Aini':72, 'depoN': 4.0, 'depoP': 0.1,
                      'depoK': 0.65},
            'neva31':{'ntubes':10, 'file': 'DWTneva31Interp.csv', 'wfile': 'nevajarvi_weather.csv',
                      'mottifile':'neva31_A.xls', 'ddepth': -1.08, 'Swidth': 30.,
                      'vonP':[5,5,4,5,5,5], 'ptype':['A','A','A','A','A','A'], 'start_date':datetime.datetime(2007,1,1), 
                      'end_date':datetime.datetime(2014,12,31), 'status': 'dry','bulk dens':122.5, 'thinning': False,
                      'vol':[127.2, 161.5], 'sfc':3, 'hdom': [16.5, 17.0], 'mark':'b+', 'Aini':79, 'depoN': 4.0, 'depoP': 0.1,
                      'depoK': 0.65},
            'neva34':{'ntubes':10, 'file': 'DWTneva34Interp.csv', 'wfile': 'nevajarvi_weather.csv',
                      'mottifile':'neva34_A.xls','ddepth': -1.08, 'Swidth': 30.,
                      'vonP':[5,5,4,5,5,5], 'ptype':['A','A','A','A','A','A'], 'start_date':datetime.datetime(2007,1,1), 
                      'end_date':datetime.datetime(2014,12,31), 'status': 'wet','bulk dens':122.5, 'thinning': False,
                      'vol':[100.4, 147.3], 'sfc':3, 'hdom': [15.3,17.1], 'mark':'b+', 'Aini':80, 'depoN': 4.0, 'depoP': 0.1,
                      'depoK': 0.65},
            'parkano11':{'ntubes':12, 'file': 'DWTparkano11Interp.csv', 'wfile': 'parkano_weather.csv',
                      'mottifile':'parkano11_A.xls','ddepth': -0.86, 'Swidth': 65.,
                      'vonP':[3,5,6,6,6,6], 'ptype':['S','S','S','S','S','S'], 'start_date':datetime.datetime(2007,1,1), 
                      'end_date':datetime.datetime(2011,12,31), 'status': 'dry','bulk dens':99.35, 'thinning': False,
                      'vol':[167.7, 192.4], 'sfc':5, 'hdom': [17.3, 18.7], 'mark':'bD', 'Aini':130, 'depoN': 4.0, 'depoP': 0.1,
                      'depoK': 0.95},
            'parkano12':{'ntubes':14, 'file': 'DWTparkano12Interp.csv', 'wfile': 'parkano_weather.csv',
                      'mottifile':'parkano12_harvennus_A.xls','ddepth': -0.89, 'Swidth': 65.,
                      'vonP':[3,5,6,6,6,6], 'ptype':['A','A','A','A','A','A'], 'start_date':datetime.datetime(2007,1,1), 
                      'end_date':datetime.datetime(2009,12,31), 'status': 'wet','bulk dens':99.35, 'thinning': True,
                      'vol':[263.,268.], 'sfc':5, 'hdom': [20.0, 20.7], 'mark':'rD', 'Aini':125, 'depoN': 4.0, 'depoP': 0.1,
                      'depoK': 0.95},

        },
        
        'thin-end':{
            'ansa11':{'ntubes':6, 'file': 'DWTansa11Interp.csv', 'wfile': 'muhos_weather.csv',
                      'mottifile':'ansa11_harvennus_Z.xls', 'ddepth': -0.25, 'Swidth': 40.,
                      'vonP':[4,6,6,6,6,6], 'ptype':['A','A','A','A','A','A'], 'start_date':datetime.datetime(2010,1,1), 
                      'end_date':datetime.datetime(2014,12,31), 'status': 'wet', 'bulk dens':122.6, 'thinning': True,
                      'vol':[98.13,121.31], 'sfc':3, 'hdom': [11.9, 13.3], 'mark':'ro', 'Aini':46, 'depoN': 4.0, 'depoP': 0.1,
                      'depoK': 0.65},
            'ansa16':{'ntubes':3, 'file': 'DWTansa16Interp.csv', 'wfile': 'muhos_weather.csv',
                      'mottifile':'ansa16_harvennus_Z.xls', 'ddepth': -0.25, 'Swidth': 40.,
                      'vonP':[4,6,6,6,6,6], 'ptype':['A','A','A','A','A','A'], 'start_date':datetime.datetime(2010,1,1), 
                      'end_date':datetime.datetime(2014,12,31), 'status': 'dry', 'bulk dens':122.6, 'thinning': True,
                      'vol':[101.4, 135.3], 'sfc':3, 'hdom': [13.1, 15.3], 'mark':'ro', 'Aini':46, 'depoN': 4.0, 'depoP': 0.1,
                      'depoK': 0.65},
           'ansa21':{'ntubes':6, 'file': 'DWTansa21Interp.csv', 'wfile': 'muhos_weather.csv',
                      'mottifile':'ansa21_A.xls', 'ddepth': -0.45, 'Swidth': 40.,
                      'vonP':[2,3,4,4,6,6], 'ptype':['A','A','A','A','A','A'], 'start_date':datetime.datetime(2010,1,1), 
                      'end_date':datetime.datetime(2014,12,31), 'status': 'wet', 'bulk dens':128.7, 'thinning': False,
                      'vol':[156.6,187.07], 'sfc':3, 'hdom': [12.8,14.6], 'mark':'bo', 'Aini':46, 'depoN': 4.0, 'depoP': 0.1,
                      'depoK': 0.65},
            'ansa26':{'ntubes':3, 'file': 'DWTansa26Interp.csv', 'wfile': 'muhos_weather.csv',
                      'mottifile':'ansa26_A.xls','ddepth': -0.45, 'Swidth': 40.,
                      'vonP':[2,3,4,4,6,6], 'ptype':['A','A','A','A','A','A'], 'start_date':datetime.datetime(2010,1,1), 
                      'end_date':datetime.datetime(2014,12,31), 'status': 'dry','bulk dens':128.7, 'thinning': False,
                      'vol':[118.9,140.86], 'sfc':3, 'hdom': [12.6, 15.4], 'mark':'bo', 'Aini':46, 'depoN': 4.0, 'depoP': 0.1,
                      'depoK': 0.55},
            'jaakkoin61':{'ntubes':6, 'file': 'DWTjaakkoin61Interp.csv', 'wfile': 'jaakkoinsuo_weather.csv',
                      'mottifile':'jaakkoin61_A.xls','ddepth': -0.85, 'Swidth': 40.,
                      'vonP':[4,8,7,7,7,7], 'ptype':['A','A','A','A','A','A'], 'start_date':datetime.datetime(2010,1,1), 
                      'end_date':datetime.datetime(2013,12,31), 'status': 'wet','bulk dens':134., 'thinning': False,
                      'vol':[155.2,172.6], 'sfc':5, 'hdom': [17.6, 18.5], 'mark':'b*', 'Aini':86,'depoN': 4.0, 'depoP': 0.1,
                      'depoK': 0.95},
            'jaakkoin62':{'ntubes':8, 'file': 'DWTjaakkoin62Interp.csv', 'wfile': 'jaakkoinsuo_weather.csv',
                      'mottifile':'jaakkoin62_A.xls','ddepth': -0.85, 'Swidth': 40.,
                      'vonP':[4,8,7,7,7,7], 'ptype':['A','A','A','A','A','A'], 'start_date':datetime.datetime(2010,1,1), 
                      'end_date':datetime.datetime(2013,12,31), 'status': 'dry','bulk dens':134., 'thinning': False,
                      'vol':[165.6,186.6], 'sfc':5, 'hdom': [18.1, 19.5], 'mark':'b*', 'Aini':93, 'depoN': 4.0, 'depoP': 0.1,
                      'depoK': 0.95},
            'koira11':{'ntubes':3, 'file': 'DWTkoira11Interp.csv', 'wfile': 'koirasuo_weather.csv',
                      'mottifile':'koira11_A.xls','ddepth': -0.85, 'Swidth': 37.,
                       'vonP':[4,4,5,6,7,7], 'ptype':['A','A','A','A','A','A'], 'start_date':datetime.datetime(2010,1,1), 
                      'end_date':datetime.datetime(2014,12,31), 'status': 'wet','bulk dens':108.6, 'thinning': False,
                      'vol':[98.17,113.7], 'sfc':2, 'hdom': [12.9, 13.9], 'mark':'bs', 'Aini':93, 'depoN': 4.0, 'depoP': 0.1,
                      'depoK': 0.65},
            'koira12':{'ntubes':3, 'file': 'DWTkoira12Interp.csv', 'wfile': 'koirasuo_weather.csv',
                      'mottifile':'koira12_A.xls','ddepth': -0.85, 'Swidth': 37.,
                       'vonP':[4,4,5,6,6,6], 'ptype':['A','A','A','A','A','A'], 'start_date':datetime.datetime(2010,1,1), 
                      'end_date':datetime.datetime(2014,12,31), 'status': 'dry','bulk dens':108.6, 'thinning': False,
                      'vol':[137.6,166.9], 'sfc':2, 'hdom': [13.2,16.4], 'mark':'bs', 'Aini':83, 'depoN': 4.0, 'depoP': 0.1,
                      'depoK': 0.65},       
            'koira21':{'ntubes':3, 'file': 'DWTkoira21Interp.csv', 'wfile': 'koirasuo_weather.csv',
                      'mottifile':'koira21_harvennus_Z.xls','ddepth': -0.85, 'Swidth': 37.,
                       'vonP':[4,4,5,6,6,6], 'ptype':['A','A','A','A','A','A'], 'start_date':datetime.datetime(2010,1,1), 
                      'end_date':datetime.datetime(2014,12,31), 'status': 'wet','bulk dens':108.6, 'thinning': True,
                      'vol':[75.37,91.3], 'sfc':2, 'hdom': [12.7, 14.5], 'mark':'rs', 'Aini':83, 'depoN': 4.0, 'depoP': 0.1,
                      'depoK': 0.65},        
            'koira22':{'ntubes':3, 'file': 'DWTkoira22Interp.csv', 'wfile': 'koirasuo_weather.csv',
                      'mottifile':'koira22_harvennus_Z.xls','ddepth': -0.85, 'Swidth': 37.,
                       'vonP':[4,4,5,6,6,6], 'ptype':['A','A','A','A','A','A'], 'start_date':datetime.datetime(2010,1,1), 
                      'end_date':datetime.datetime(2014,12,31), 'status': 'dry','bulk dens':108.6, 'thinning': True,
                      'vol':[72.32,87.13], 'sfc':2, 'hdom': [11.1,14.3], 'mark':'rs', 'Aini':88, 'depoN': 4.0, 'depoP': 0.1,
                      'depoK': 0.95},
            'neva11':{'ntubes':6, 'file': 'DWTneva11Interp.csv', 'wfile': 'nevajarvi_weather.csv',
                      'mottifile':'neva11_A.xls','ddepth': -1.03, 'Swidth': 30.,
                      'vonP':[5,5,5,4,4,4], 'ptype':['A','A','A','A','A','A'], 'start_date':datetime.datetime(2009,1,1), 
                      'end_date':datetime.datetime(2014,12,31), 'status': 'dry','bulk dens':113.25, 'thinning': False,
                      'vol':[178.69, 227.5], 'sfc':3, 'hdom': [16.1, 17.8], 'mark':'b+', 'Aini':88, 'depoN': 4.0, 'depoP': 0.1,
                      'depoK': 0.65},
            'neva14':{'ntubes':6, 'file': 'DWTneva14Interp.csv', 'wfile': 'nevajarvi_weather.csv',
                      'mottifile':'neva14_A.xls', 'ddepth': -1.03, 'Swidth': 30.,
                      'vonP':[5,5,5,4,4,4], 'ptype':['A','A','A','A','A','A'], 'start_date':datetime.datetime(2009,1,1), 
                      'end_date':datetime.datetime(2014,12,31), 'status': 'wet','bulk dens':113.25, 'thinning': False,
                      'vol':[158.3,191.4], 'sfc':3, 'hdom': [16.5, 18.4], 'mark':'b+', 'Aini':88, 'depoN': 4.0, 'depoP': 0.1,
                      'depoK': 0.65},
            'neva21':{'ntubes':7, 'file': 'DWTneva21Interp.csv', 'wfile': 'nevajarvi_weather.csv',
                      'mottifile':'neva21_harvennus_Z.xls','ddepth': -1.07, 'Swidth': 30.,
                      'vonP':[4,4,4,4,4,4], 'ptype':['A','A','A','A','A','A'], 'start_date':datetime.datetime(2009,1,1), 
                      'end_date':datetime.datetime(2014,12,31), 'status': 'dry','bulk dens':97.8, 'thinning': True,
                      'vol':[82.3,109.89], 'sfc':3, 'hdom': [15.7, 16.7], 'mark':'r+', 'Aini':93, 'depoN': 4.0, 'depoP': 0.1,
                      'depoK': 0.65},   
            'neva24':{'ntubes':6, 'file': 'DWTneva24Interp.csv', 'wfile': 'nevajarvi_weather.csv',
                      'mottifile':'neva24_harvennus_Z.xls','ddepth': -1.07, 'Swidth': 30.,
                      'vonP':[4,4,4,4,4,4], 'ptype':['A','A','A','A','A','A'], 'start_date':datetime.datetime(2009,1,1), 
                      'end_date':datetime.datetime(2014,12,31), 'status': 'wet','bulk dens':97.8, 'thinning': True,
                      'vol':[93.6,124.7], 'sfc':3, 'hdom': [14.6, 17.1], 'mark':'r+', 'Aini':88, 'depoN': 4.0, 'depoP': 0.1,
                      'depoK': 0.65},
            'neva31':{'ntubes':10, 'file': 'DWTneva31Interp.csv', 'wfile': 'nevajarvi_weather.csv',
                      'mottifile':'neva31_A.xls', 'ddepth': -1.08, 'Swidth': 30.,
                      'vonP':[5,5,4,5,5,5], 'ptype':['A','A','A','A','A','A'], 'start_date':datetime.datetime(2009,1,1), 
                      'end_date':datetime.datetime(2014,12,31), 'status': 'dry','bulk dens':122.5, 'thinning': False,
                      'vol':[137.6,161.5], 'sfc':3, 'hdom': [16.5, 17.0], 'mark':'b+', 'Aini':88, 'depoN': 4.0, 'depoP': 0.1,
                      'depoK': 0.65},
            'neva34':{'ntubes':10, 'file': 'DWTneva34Interp.csv', 'wfile': 'nevajarvi_weather.csv',
                      'mottifile':'neva34_A.xls','ddepth': -1.08, 'Swidth': 30.,
                      'vonP':[5,5,4,5,5,5], 'ptype':['A','A','A','A','A','A'], 'start_date':datetime.datetime(2009,1,1), 
                      'end_date':datetime.datetime(2014,12,31), 'status': 'wet','bulk dens':122.5, 'thinning': False,
                      'vol':[111.5,147.3], 'sfc':3, 'hdom': [15.3,17.1], 'mark':'b+', 'Aini':88, 'depoN': 4.0, 'depoP': 0.1,
                      'depoK': 0.65},
            'parkano11':{'ntubes':12, 'file': 'DWTparkano11Interp.csv', 'wfile': 'parkano_weather.csv',
                      'mottifile':'parkano11_A.xls','ddepth': -0.86, 'Swidth': 65.,
                      'vonP':[3,5,6,6,6,6], 'ptype':['S','S','S','S','S','S'], 'start_date':datetime.datetime(2010,1,1), 
                      'end_date':datetime.datetime(2011,12,31), 'status': 'dry','bulk dens':99.35, 'thinning': False,
                      'vol':[180.,192.4], 'sfc':5, 'hdom': [17.3, 18.7], 'mark':'bD', 'Aini':135, 'depoN': 4.0, 'depoP': 0.1,
                      'depoK': 0.95},
            'parkano12':{'ntubes':14, 'file': 'DWTparkano12Interp.csv', 'wfile': 'parkano_weather.csv',
                      'mottifile':'parkano12_harvennus_Z.xls','ddepth': -0.89, 'Swidth': 65.,
                      'vonP':[3,5,6,6,6,6], 'ptype':['A','A','A','A','A','A'], 'start_date':datetime.datetime(2010,1,1), 
                      'end_date':datetime.datetime(2011,12,31), 'status': 'wet','bulk dens':99.35, 'thinning': True,
                      'vol':[155.,173.5], 'sfc':5, 'hdom': [20.0, 20.7], 'mark':'rD', 'Aini':134, 'depoN': 4.0, 'depoP': 0.1,
                      'depoK': 0.95},

        },
        }
    
    return sites[period]

def get_photo_para(site):
        
    photopara = {
              'All data':
                  {'beta':0.513,
                   'gamma':0.0196,
                   'kappa': -0.389,
                   'tau':7.2,
                   'X0': -4.0,
                   'Smax':17.3,
                   'alfa': 1.,
                   'nu': 5.
                   },
              'Sodankyla':
                  {'beta':0.831,
                   'gamma':0.065,
                   'kappa': -0.150,
                   'tau':10.2,
                   'X0': -0.9,
                   'Smax':16.4,
                   'alfa': 1.,
                   'nu': 5.
                   },
              'Hyytiala':
                  {'beta':0.504,
                   'gamma':0.0303,
                   'kappa': -0.235,
                   'tau':11.1,
                   'X0': -3.1,
                   'Smax':17.3,
                   'alfa': 1.,
                   'nu': 5.
                   },
              'Norunda':
                  {'beta':0.500,
                   'gamma':0.0220,
                   'kappa': -0.391,
                   'tau':5.7,
                   'X0': -4.0,
                   'Smax':17.6,
                   'alfa':1.062,
                   'nu': 11.27,
                   },
              'Tharandt':
                  {'beta':0.742,
                   'gamma':0.0267,
                   'kappa': -0.512,
                   'tau':1.8,
                   'X0': -5.2,
                   'Smax':18.5,
                   'alfa':1.002,
                   'nu': 442.
                   },
              'Bray':
                  {'beta':0.459,
                   'gamma':-0.000669,
                   'kappa': -0.560,
                   'tau':2.6,
                   'X0': -17.6,
                   'Smax':45.0,
                   'alfa':0.843,
                   'nu': 2.756,
                   }
                   }
    return photopara[site]